### ISSUE TITLE
Some additions

### ISSUE THREAD

**Issue by waja** [topheman/m102-notes#1]
Feel free to cherry-pick or merge from https://github.com/waja/m102-notes

Cheers, Jan.

**Comment by topheman** [comment]
Thanks @waja , will do.

I'll get to it until the end of the week.

**Comment by topheman** [comment]
I merged your branch and rebased it to pick only the commits about the courses. I added you to the contributors section I created https://github.com/topheman/m102-notes#contributing .

Thanks for your contribution @waja 

Tophe
